# Generated by Django 2.1.7 on 2019-03-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api_v1', '0003_auto_20190319_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='amount',
            new_name='money',
        ),
        migrations.RenameField(
            model_name='balance',
            old_name='amount_currency',
            new_name='money_currency',
        ),
    ]
