# Generated by Django 2.1.7 on 2019-03-24 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api_v1', '0005_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('email',)},
        ),
        migrations.AlterField(
            model_name='balance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='payment_api_v1.Account'),
        ),
    ]
