# Generated by Django 2.1.7 on 2019-03-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_api_v1', '0006_auto_20190324_0811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-datetime',)},
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'success'), (2, 'not_enough_money'), (3, 'system_failure'), (4, 'currencies_dont_match')], default=0),
        ),
    ]
